const db = require('./database')
const Student = require('./student')
const Campus = require('./campus')

const seed = async () => {
  await db.sync({ force: true });
  const campuses = await Promise.all([
    Campus.create({name: 'CCNY', address: 'NYC, NY', description:'Stay away from the nac ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'Bard', address: 'Red Hook, NY', description:'Home of the pond of perception'}),
    Campus.create({name: 'Columbia', address: 'NYC, NY', description:'bicycle grounds'}),
    Campus.create({name: 'UoM', address: 'MIA, FL', description:'miami'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Cs amsterdam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CCNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvA', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'UvO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUNY', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'Vu', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),
    Campus.create({name: 'CUAMO', address: 'amsterdam ave 142nd st', description:'STAY AWAY FROM NAC ):'}),
    Campus.create({name: 'CUOMO', address: 'Amsterdam, NL', description:'Geschiedenis Adam'}),

  ])
  const students = await Promise.all([
    Student.create({firstName: 'Primo', lastName: 'Gill', email: 'primo@gmail.com', gpa: 3.5, campusId: 1}),
    Student.create({firstName: 'Manegbe', lastName: 'Eben', email: 'eben@gmail.com', gpa: 3.9, campusId: 1}),
    Student.create({firstName: 'Oskar', lastName: 'Gill', email: 'oskar@gmail.com', gpa: 4.0, campusId: 2}),
    Student.create({firstName: 'Mason', lastName: 'Porter Brown', email: 'mason@gmail.com', gpa: 1.5, campusId: 3}),
    Student.create({firstName: 'Jonathan', lastName: 'Gill', email: 'jonathan@gmail.com', gpa: 2.8, campusId: 4}),
    Student.create({firstName: 'Evelien', lastName: 'Ledeboer', email: 'evelien@gmail.com', gpa: 4.0, campusId: 4}),
    Student.create({firstName: 'Randy', lastName: 'Pierre', email: 'randy@gmail.com', gpa: 3.0, campusId: 5}),
    Student.create({firstName: 'Matteo', lastName: 'Florio', email: 'matteo@gmail.com', gpa: 3.0, campusId: 5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
    Student.create({firstName: 'Primov2', lastName: 'Gillv2', email: 'primov2@gmail.com', gpa: 3.5}),
  ])
  console.log(`
    Seeding successful!
  `);
};

module.exports = seed;
